### ISSUE TITLE
Undefined function or variable 'row'

### ISSUE THREAD

**Issue by kouichi-c-nakamura** [ome/bio-formats-matlab#5]
When opening an image with LUT (`isempty(colorMaps) == false`), `bfopen` failed to work. Both variables `row` and `col` in line 163 are not defined in `bfopen`, so it appears to be a bug (version 5.8.2).

```
Undefined function or variable 'row'.
Error in bfopen (line 163)
            m = newMap(row, col) < 0; 

```

I'm happy to upload a demo data for this if needed.

Meanwhile, I disabled the `colorMaps` by following:

```matlab
% line 161 of bfopen
if 0 %~isempty(colorMaps{s, i})
    newMap = colorMaps{s, i};
    m = newMap(row, col) < 0;
    newMap(m) = newMap(m) + bppMax;
    colorMaps{s, i} = newMap / (bppMax - 1);
end

```

**Comment by kouichi-c-nakamura** [comment]
Actually, I've realized that the source code in this repo is different from 5.8.2. Is the released version behind?

https://github.com/ome/bio-formats-matlab/blob/68993478fcd64acf0847204d4d52f9541c95e7d4/src/bfopen.m#L159-L165

**Comment by rleigh-codelibre** [comment]
This repository is not currently used for any released version of Bio-Formats.  We will be removing the matlab code from the main bioformats repository and using this one for a future release, but right now it's not ready for production use and isn't completely up-to-date with the very latest Bio-Formats code changes.  Please could you open an issue against https://github.com/openmicroscopy/bioformats/ (I would move the issue directly, but github doesn't support this unfortunately).


Kind regards,
Roger

**Comment by kouichi-c-nakamura** [comment]
Oh, I see. Thanks.

I've done.
https://github.com/openmicroscopy/bioformats/issues/3134
